# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-06 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type information')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the category')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the place')),
                ('city', models.CharField(max_length=100, verbose_name='Name of the city')),
                ('state', models.CharField(max_length=100, verbose_name='Name of the state')),
                ('country', models.CharField(max_length=200, verbose_name='Name of the country')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='exploreapp.Category')),
            ],
        ),
    ]
